# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-09-26 10:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Customer',
            new_name='CustomerORM',
        ),
    ]
